version: "3.3"

services:

  redis:
    image: redis
    entrypoint: redis-server --appendonly yes

  mongo:
    image: mongo:4.4
    volumes:
      - data_db:/data/db

  application:
    build:
      context: .
    security_opt:
      - no-new-privileges:true
    depends_on:
      - mongo
      - redis
    environment:
      config: base
volumes:
  data_db:
