version: "3.7"

services:

  application:
    build: 
      dockerfile: Dockerfile.local
    environment:
      config: compose
      FLASK_DEBUG: 1
    ports:
      - 5004:5004
    volumes:
      - ./:/srv
